name: Draft PDF
on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
      - '!paper/paper.pdf'

permissions:
  contents: write

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: paper
          path: paper/paper.pdf


      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v10
        with:
          message: '(auto) Paper PDF Draft'
          add: 'paper/paper.pdf' # 'paper/*.pdf' to commit all PDFs in the paper directory
          default_author: github_actions
          push: origin HEAD:${{ github.ref_name }}


